def ayudaPrincipal():
	print ("======================================================================")
	print ("=          ALGORITMOS CRIPTOGRAFICOS                                 =")
	print ("=                                                                    =")
	print ("=  Sintaxis: python main.py <algoritmo>                              =")
	print ("=  <algoritmo>:                                                      =")
	print ("=        -pf 	Algoritmo Playfair.                                  =")
	print ("=        -ks 	Algoritmo Kasiski.                                   =")
	print ("=        -mh 	Maquina de Hagelin.                                  =")
	print ("=        -lz	Algoritmo de Lorenz.                                 =")
	print ("=        -me 	Maquina de Enigma.                                   =")
	print ("=                                                                    =")
	print ("=  Consultar la ayuda de un algoritmo en especifico.                 =")
	print ("=                        Sintaxis: python main <algoritmo> -a        =")
	print ("=                                                                    =")
	print ("=                                                                    =")
	print ("=  Universidad del Cauca                                             =")
	print ("=  Introducción a la Criptogradia                                    =")
	print ("=  Docente: Siler Amador Donado                                      =")
	print ("=  Elaborado por: Jorge Tunubala - Alejandro Méndez A                =")
	print ("=  Semestre: 2018-2                                                  =")
	print ("=                                                                    =")
	print ("======================================================================")
	
def ayudaEspecifica():
	print ("======================================================================")
	print ("=  Consultar la ayuda de un algoritmo en especifico.                 =")
	print ("=                        Sintaxis: python main.py <algoritmo> -a     =")
	print ("=                                                                    =")
	print ("======================================================================")

def ayudaAlgoritmo(tipo):
	if tipo == "-pf":
		alg_Playfair()
	elif tipo == "-ks":
		alg_Kasiski()
	elif tipo == "-mh":
		maq_Hagelin()
	elif tipo == "-lz":
		maq_Colossus()
	elif tipo == "-me":
		maq_Enigma()

def alg_Playfair():
	print ("=====================================================================================================")
	print ("=                                     ALGORITMO     PLAYFAIR                                        =")
	print ("=                                                                                                   =")
	print ("=  Sintaxis: python main.py -pf <modo> -e <ArchivoEntrada> -k <ArchivoClave>                        =")
	print ("=                                                                                                   =")
	print ("=  <modo>:    -c para cifrar el archivo <ArchivoEntrada>                                            =")
	print ("=             -d para descifrar el archivo <ArchivoEntrada>                                         =")
	print ("=                                                                                                   =")
	print ("=  <ArchivoEntrada>: Nombre del archivo de entrada.                                                 =")
	print ("=                                                                                                   =")
	print ("=  <ArchivoClave>: nombre del archivo el cual contiene la clave necesaria en el algoritmo           =")
	print ("=                                                                                                   =")
	print ("=  Si <modo> es -c, el archivo de salida es <ArchivoEntrada> con extension .cif                     =")
	print ("=  Si <modo> es -d, el archivo de salida es <ArchivoEntrada> con extension .dec                     =")
	print ("=                                                                                                   =")
	print ("=  El archivo que contiene la clave debe estar en una sola linea, puede contener espacios.          =")
	print ("=     Importante no contener simbolos. (Solo alfabeto a-z A-Z).                                     =")	
	print ("=                                                                                                   =")
	print ("=  Ejemplo1:       Para Cifrar: python3 main.py -pf -c -e quijote.txt -k clavePlayfair.key           =")
	print ("=                  Para Descifrar: python3 main.py -pf -d -e quijote.txt.cif -k clavePlayfair.key    =")
	print ("=  Ejemplo2:       Para Cifrar: python3 main.py -pf -c -e MobyDick.txt -k clavePlayfair.key           =")
	print ("=                  Para Descifrar: python3 main.py -pf -d -e MobyDick.txt.cif -k clavePlayfair.key    =")
	print ("=                                                                                                   =")
	print ("=  Elaborado por:    Jorge Alfredo Tunubala Ramirez    jorgetunubala@unicauca.edu.co                =")
	print ("=                    Alejandro Méndez Astudillo        victoralemendez@unicauca.edu.co              =")
	print ("=====================================================================================================")

def alg_Kasiski():
	print ("=====================================================================================================")
	print ("=                                     ALGORITMO     KASISKI                                         =")
	print ("=                                                                                                   =")
	print ("=  Sintaxis: python main.py -ks <modo> -e <ArchivoEntrada> -k <ArchivoClave>                        =")
	print ("=                                                                                                   =")
	print ("=  <modo>:    -c para cifrar el archivo <ArchivoEntrada>                                            =")
	print ("=             -d para descifrar el archivo <ArchivoEntrada>                                         =")
	print ("=                                                                                                   =")
	print ("=  <ArchivoEntrada>: Nombre del archivo de entrada.                                                 =")
	print ("=                                                                                                   =")
	print ("=  <ArchivoClave>: nombre del archivo el cual contiene la clave necesaria en el algoritmo           =")
	print ("=                                                                                                   =")
	print ("=  Si <modo> es -c, el archivo de salida es <ArchivoEntrada> con extension .cif                     =")
	print ("=  Si <modo> es -d, el archivo de salida es <ArchivoEntrada> con extension .dec                     =")
	print ("=                                                                                                   =")
	print ("=  El archivo que contiene la clave debe estar en una sola linea, puede contener espacios.          =")
	print ("=     Importante no contener simbolos. (Solo alfabeto a-z A-Z).                                     =")	
	print ("=                                                                                                   =")
	print ("=  Ejemplo1:       Para Cifrar: python3 main.py -ks -c -e quijote.txt -k claveKasiski.key            =")
	print ("=                  Para Descifrar: python3 main.py -ks -d -e quijote.txt.cif -k claveKasiski.key     =")
	print ("=  Ejemplo2:       Para Cifrar: python3 main.py -ks -c -e MobyDick.txt -k claveKasiski.key            =")
	print ("=                  Para Descifrar: python3 main.py -ks -d -e MobyDick.txt.cif -k claveKasiski.key     =")
	print ("=                                                                                                   =")
	print ("=  Elaborado por:    Jorge Alfredo Tunubala Ramirez    jorgetunubala@unicauca.edu.co                =")
	print ("=                    Alejandro Méndez Astudillo        victoralemendez@unicauca.edu.co              =")
	print ("=====================================================================================================")

def maq_Hagelin():
	print ("=====================================================================================================")
	print ("=                                     MAQUINA    HAGELIN                                            =")
	print ("=                                                                                                   =")
	print ("=  Sintaxis: python main.py -mh <modo> -e <ArchivoEntrada> -k <ArchivoClave>                        =")
	print ("=                                                                                                   =")
	print ("=  <modo>:    -c para cifrar el archivo <ArchivoEntrada>                                            =")
	print ("=             -d para descifrar el archivo <ArchivoEntrada>                                         =")
	print ("=                                                                                                   =")
	print ("=  <ArchivoEntrada>: Nombre del archivo de entrada.                                                 =")
	print ("=                                                                                                   =")
	print ("=  <ArchivoClave>: nombre del archivo el cual contiene la clave necesaria en el algoritmo           =")
	print ("=                                                                                                   =")
	print ("=  Si <modo> es -c, el archivo de salida es <ArchivoEntrada> con extension .cif                     =")
	print ("=  Si <modo> es -d, el archivo de salida es <ArchivoEntrada> con extension .dec                     =")
	print ("=                                                                                                   =")
	print ("=  El archivo que contiene la clave debe estar en una sola linea, puede contener espacios.          =")
	print ("=     Importante no contener simbolos. (Solo alfabeto a-z A-Z).                                     =")	
	print ("=                                                                                                   =")
	print ("=  Ejemplo1:       Para Cifrar: python3 main.py -mh -c -e quijote.txt -k claveMaq_Hagelin.key        =")
	print ("=                  Para Descifrar: python3 main.py -mh -d -e quijote.txt.cif -k claveMaq_Hagelin.key =")
	print ("=  Ejemplo2:       Para Cifrar: python3 main.py -mh -c -e MobyDick.txt -k claveMaq_Hagelin.key        =")
	print ("=                  Para Descifrar: python3 main.py -mh -d -e MobyDick.txt.cif -k claveMaq_Hagelin.key =")
	print ("=                                                                                                   =")
	print ("=  Elaborado por:    Jorge Alfredo Tunubala Ramirez    jorgetunubala@unicauca.edu.co                =")
	print ("=                    Alejandro Méndez Astudillo        victoralemendez@unicauca.edu.co              =")
	print ("=====================================================================================================")

def maq_Colossus():
	print ("=====================================================================================================")
	print ("=                                      ALGORITMO    LORENZ                                          =")
	print ("=                                                                                                   =")
	print ("=  Sintaxis: python main.py -mc <modo> -e <ArchivoEntrada> -k <ArchivoClave>                        =")
	print ("=                                                                                                   =")
	print ("=  <modo>:    -c para cifrar el archivo <ArchivoEntrada>                                            =")
	print ("=             -d para descifrar el archivo <ArchivoEntrada>                                         =")
	print ("=                                                                                                   =")
	print ("=  <ArchivoEntrada>: Nombre del archivo de entrada.                                                 =")
	print ("=                                                                                                   =")
	print ("=  <ArchivoClave>: nombre del archivo el cual contiene la clave necesaria en el algoritmo           =")
	print ("=                                                                                                   =")
	print ("=  Si <modo> es -c, el archivo de salida es <ArchivoEntrada> con extension .cif                     =")
	print ("=  Si <modo> es -d, el archivo de salida es <ArchivoEntrada> con extension .dec                     =")
	print ("=                                                                                                   =")	
	print ("=  Para cambiar la configuracion del algoritmo modifique el archivo config-lorenz.cf                =")
	print ("=                                                                                                   =")
	print ("=  Ejemplo1:       Para Cifrar: python3 main.py -lz -c -e quijote.txt -k config-lorenz.cf          =")
	print ("=                  Para Descifrar: python3 main.py -lz -d -e quijote.txt.cif -k config-lorenz.cf   =")
	print ("=  Ejemplo2:       Para Cifrar: python3 main.py -lz -c -e MobyDick.txt -k config-lorenz.cf          =")
	print ("=                  Para Descifrar: python3 main.py -lz -d -e MobyDick.txt.cif -k config-lorenz.cf   =")
	print ("=                                                                                                   =")
	print ("=  Elaborado por:    Jorge Alfredo Tunubala Ramirez    jorgetunubala@unicauca.edu.co                =")
	print ("=                    Alejandro Méndez Astudillo        victoralemendez@unicauca.edu.co              =")
	print ("=====================================================================================================")

def maq_Enigma():
	print ("=====================================================================================================")
	print ("=                                     MAQUINA ENIGMA                                                =")
	print ("=                                                                                                   =")
	print ("=  Sintaxis: python main.py -me <modo> -e <ArchivoEntrada> -k <ArchivoClave>                        =")
	print ("=                                                                                                   =")
	print ("=  <modo>:    -c para cifrar el archivo <ArchivoEntrada>                                            =")
	print ("=             -d para descifrar el archivo <ArchivoEntrada>                                         =")
	print ("=                                                                                                   =")
	print ("=  <ArchivoEntrada>: Nombre del archivo de entrada.                                                 =")
	print ("=  <ArchivoClave>: nombre del archivo el cual contiene la clave necesaria en el algoritmo           =")
	print ("=                                                                                                   =")
	print ("=  Si <modo> es -c, el archivo de salida es <ArchivoEntrada> con extension .cif                     =")
	print ("=  Si <modo> es -d, el archivo de salida es <ArchivoEntrada> con extension .dec                     =")
	print ("=                                                                                                   =")
	print ("=  Para cambiar la configuracion del algoritmo modifique el archivo config-enigma.cf                =")
	print ("=                                                                                                   =")
	print ("=  Ejemplos:       Para Cifrar: python3 main.py -me -c -e quijote.txt -k config-enigma.cf           =")
	print ("=                  Para Descifrar: python3 main.py -me -d -e quijote.txt -k config-enigma.cf        =")
	print ("=                                                                                                   =")
	print ("=  Elaborado por:    Jorge Alfredo Tunubala Ramirez    jorgetunubala@unicauca.edu.co                =")
	print ("=                    Alejandro Méndez Astudillo        victoralemendez@unicauca.edu.co              =")
	print ("=====================================================================================================")
